spring.application.name=gestor-tareas

spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_tareas
spring.datasource.username=postgres
spring.datasource.password=postgre92

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
